docroot/sites/all/modules/custom/fsa_feedback/js/fsa-feedback.js

Any link to the feedback form using the href `#feedback-form` will now open up the feedback form and scroll smoothly down the page to its location.
If JavaScript is not enabled, the form will already be displayed, and the link will just go to that bookmark, thereby achieving the same result.
@todo Include the page title in the feedback emails and reports
[ Partial fix for #10229 ]

Enable in-page links to the feedback form

---

docroot/sites/all/modules/custom/fsa_review_date/fsa_review_date.info
docroot/sites/all/modules/custom/fsa_review_date/fsa_review_date.module
docroot/sites/all/modules/custom/local/local.module

The links in the review date reminder emails were previously using the standard domain, but they need to use the admin domain to enable users to view the reports.
1. Modified the function `local_get_site_domain()` to accept an additional parameter for `$protocol`
2. Modified the function that builds the review date emails to use this function and specify `TRUE` for the `$admin` parameter, as well as `https` for the new `$protocol` parameter.
[ Partial fix for #10143 ]

Ensure links in review date emails use admin domain

---

docroot/sites/all/modules/custom/fsa_review_date/fsa_review_date.info
docroot/sites/all/modules/custom/fsa_review_date/fsa_review_date.module
docroot/sites/all/modules/custom/local/local.module

The links in the review date reminder emails were previously using the standard domain, but they need to use the admin domain to enable users to view the reports.
1. Modified the function `local_get_site_domain()` to accept an additional parameter for `$protocol`
2. Modified the function that builds the review date emails to use this function and specify `TRUE` for the `$admin` parameter, as well as `https` for the new `$protocol` parameter.
[ Partial fix for #10143 ]

Master: Ensure links in review date emails use admin domain

---

docroot/sites/all/modules/contrib/crazyegg/LICENSE.txt
docroot/sites/all/modules/contrib/crazyegg/README.txt
docroot/sites/all/modules/contrib/crazyegg/crazyegg.info
docroot/sites/all/modules/contrib/crazyegg/crazyegg.module
docroot/sites/all/modules/contrib/crazyegg/includes/admin.inc
docroot/sites/all/modules/patches/FSA-10248-crazyegg-add-cache-breaker.patch
docroot/sites/all/modules/patches/FSA-10248-crazyegg-update-javascript-host.patch
docroot/sites/all/modules/patches/FSA-10248-enable-choice-of-code-rendering.patch
docroot/sites/all/modules/patches/PATCHED.txt

Installed a patched version of the contrib CrazyEgg module: **7.x-1.0**
The module has been patched as follows:
1. The cache-breaking code has been added to the JavaScript link
2. The JavaScript host has been updated
3. A new option has been to the admin interface to enable administrators to choose where the JavaScript should be rendered - header or footer
All patches are stored in the patches folder.
[ Partial fix for #10248 ]

Install CrazyEgg 7.x-1.0

---

docroot/sites/all/modules/custom/national_archives/national_archives.module

When a National Archives redirect is created, we clear the Drupal page cache. In some circumstances this is unnecessary, such as when editing a node, but when bulk operations are carried out, the page cache isn't getting cleared.

Add cache clearing function for National Archives

---

docroot/sites/all/modules/custom/fsa_review_date/fsa_review_date.module

When saving the review date, we were converting it to a timestamp, assuming that the input was a value from the form, which is a string.
However, in bulk operations where a node already has a review date set, the review date will already be a timestamp, so trying to convert it causes an error.
To fix it, we check first whether the value is numeric, and if so, we use it as is.
[ Fixes #10262 ]

Check review date format before converting

---

docroot/sites/all/modules/custom/national_archives/national_archives.info

The National Archives module is currently dependent on at least version **7.x-1.0-rc3** of the Redirect module due to a change in the API.
Previous versions of the module do not use the concept of a status for a redirect, which is used by the National Archives module.
@todo Make this module backwards compatible by deleting redirects if there is no ability to disable them.

Make National Archives dependent on specific version of redirect

---

docroot/sites/all/themes/site_frontend/template.php

In order to fix a bug whereby nodes sometimes inherit the custom CSS attached to other nodes, we check that any CSS supplied by CPN is removed if it isn't for the current node's nid.
[ Fixes #10265 ]

Add implementation of hook_css_alter()

---

docroot/sites/all/themes/site_frontend/includes/external_libraries.inc
docroot/sites/all/themes/site_frontend/preprocess/page.preprocess.inc
docroot/sites/all/themes/site_frontend/template.php

Added the JavaScript file requested by Atif to enable Google Charts.
The external library is included via a new hook `hook_external_libraries()`, which is called via a new function in the site_frontend theme's template.php file.
Links to the JavaScript files are then added via an implementation of `drupal_add_js()` called in `site_frontend_preprocess_page()`
@todo Add ability to administer external libraries via the admin UI
@todo Add ability to determine the pages on which the libraries are included
[ Fixes [#10281](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=779) ]

Add google charts javascript code

---

docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.admin.inc
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.api.php
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.info
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.module

This module provides an extensible framework for validating filenames based on various criteria.
After deploying the code, the module will need to be enabled - either via the Drupal admin UI or using Drush: `drush en fsa_filename_validation --y`
Remember to clear the caches once the module is enabled
Configure the module
-----------------------------
Once the module has been enabled, go to **Admin > Configuration > Media > File settings > Filename validation settings** and configure the validators to be used.
[ Partial fix for [#10282](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=780) ]

Develop: Create FSA filename validation module

---

docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.api.php
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.module

Added the ability for filename validators to provide help text for display on file upload forms.
This is done by overriding the existing theme function for file upload help text and then adding elements to each of the validator definitions.
Help text can be provided as a string or by a callback function in a similar way to error messages.
[ Partial fix for #10282 ]

Develop: Add file upload help text

---

docroot/sites/all/modules/custom/fsa_search_spellcheck/css/search-spelling-suggestions.css
docroot/sites/all/modules/custom/fsa_search_spellcheck/css/search-spelling-suggestions.css.map
docroot/sites/all/modules/custom/fsa_search_spellcheck/fsa_search_spellcheck.info
docroot/sites/all/modules/custom/fsa_search_spellcheck/fsa_search_spellcheck.module
docroot/sites/all/modules/custom/fsa_search_spellcheck/plugins/facetapi/url_processor_fsa_exposed_facets.inc
docroot/sites/all/modules/custom/fsa_search_spellcheck/sass/search-spelling-suggestions.scss
docroot/sites/all/modules/custom/fsa_search_spellcheck/theme/search-spelling-suggestions.tpl.php

Created a new module to provide automatic spelling suggestions using Apach Solr. It works in much the same way as Google's spelling suggestions, automatically substituting the best fit terms, but giving users a link to search for their original terms.
@todo Provide an admin interface for configuration.
[ Partial fix for [#10176](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=674) ]

Develop: 	Create search spelling suggestions module

---

docroot/sites/all/modules/custom/local/local.module
docroot/sites/all/modules/custom/national_archives/national_archives.module

Changed the way that committee pages are handled by the National Archives module.
* Added new hooks to the National Archives module to enable other modules to alter the site URL and the page URL, as well as the National Archives base URL if desired.
* Added an implementation of `hook_national_archives_site_url_alter()` in the *local* module to take account of committee domains. If a URL looks like a committee URL, we alter the site URL and remove the committee stem. We do this when expanding the National Archives URL to make it more future-proof.

Develop: Handle committee URLs in National Archives

---

docroot/sites/all/modules/custom/siteimprove/siteimprove.admin.inc
docroot/sites/all/modules/custom/siteimprove/siteimprove.api.php
docroot/sites/all/modules/custom/siteimprove/siteimprove.info
docroot/sites/all/modules/custom/siteimprove/siteimprove.install
docroot/sites/all/modules/custom/siteimprove/siteimprove.module
docroot/sites/all/modules/custom/siteimprove/theme/siteimprove-analytics-javascript.tpl.php

Created a basic module to support integration with SiteImprove.
Currently does the following:
* Adds the SiteImprove JavaScript analytics code
* Adds meta tags for CMS deeplinking
Once the code is deployed, the module will need to be enabled, either through the Drupal admin UI or via Drush: `drush en siteimprove --y`
Once that's done, the caches will need to be cleared: `drush cc all`
Add the SiteImprove account code
----------------------------------------------
Once the module is enabled, the account code will need to be entered via the Drupal admin interface. This is under Admin > Configuration > Web services > Siteimprove
[ Partial fix for [#10286](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=787) and …

Develop: Create SiteImprove module

---

docroot/sites/all/modules/custom/siteimprove/siteimprove.admin.inc
docroot/sites/all/modules/custom/siteimprove/siteimprove.api.php
docroot/sites/all/modules/custom/siteimprove/siteimprove.info
docroot/sites/all/modules/custom/siteimprove/siteimprove.install
docroot/sites/all/modules/custom/siteimprove/siteimprove.module
docroot/sites/all/modules/custom/siteimprove/theme/siteimprove-analytics-javascript.tpl.php

Created a basic module to support integration with SiteImprove.
Currently does the following:
* Adds the SiteImprove JavaScript analytics code
* Adds meta tags for CMS deeplinking
Once the code is deployed, the module will need to be enabled, either through the Drupal admin UI or via Drush: `drush en siteimprove --y`
Once that's done, the caches will need to be cleared: `drush cc all`
Add the SiteImprove account code
----------------------------------------------
Once the module is enabled, the account code will need to be entered via the Drupal admin interface. This is under Admin > Configuration > Web services > Siteimprove
[ Partial fix for [#10286](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=787) and …

Create SiteImprove module

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

Currently, the feedback module captures only the path of a page, not the query string. However, it is useful to be able to see the query string for failed searches and similar pages.
Modified the form to capture the query string, and also used `hook_feedback_insert()` to modify the url property of the feedback entry - if necessary.
[ Partial fix for [#10287](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=7850) ]

Develop: Allow feedback messages to capture query strings

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

In our custom feedback form submit handler, we unset the feedback entry's url property if it's blank. Otherwise it won't get set at all in the original contrib module's `feedback_save()` function.
[ Partial fix for #10287 ]

Develop: Unset feedback entry URL if blank

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

Instead of setting the URL on save, we set it when the
form is submitted, thereby avoiding having to re-save the entry
entity.
Need to test this with edit.
[ Partial fix for #10287 ]

Use more elegant method to set feedback URLs

---

docroot/sites/all/modules/custom/siteimprove/siteimprove.module

Was previously using `hook_node_view()` to add the meta tags to the page. However, on the FSA site, this was being triggered by an embedded node that was being displayed in 'full' view mode.
Instead, use an implementation of `template_preprocess_page()` to ensure that the node is the main page one.
[ Partial fix for [#10289](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=787) ]

Develop: Change implementation for SiteImprove meta tags

---

docroot/sites/all/modules/custom/local/local.module

Added an implementation of `hook_siteimprove_editing_page_options_alter()` in the local module.
This ensures that if the SiteImprove editing page URL meta tag is present it uses the proper admin URL, not the front-end domain.
[ Partial fix for #10289 ]

Add implementation of hook_siteimprove_editing_page_options_alter()

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

Currently, the feedback module captures only the path of a page, not the query string. However, it is useful to be able to see the query string for failed searches and similar pages.
Modified the form to capture the query string, and also used made a change to the custom submit handler for the feedback form to set the URL property of the `$entry` object before saving. Because the `url` property is set prior to saving, the contributed Feedback module's `feedback_save()` function doesn't try to set it without the query string.
[ Partial fix for [#10287](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=7850) ]

Allow feedback messages to capture query strings

---

docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.admin.inc
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.api.php
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.info
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.module

This module provides an extensible framework for validating filenames based on various criteria.
After deploying the code, the module will need to be enabled - either via the Drupal admin UI or using Drush: `drush en fsa_filename_validation --y`
Remember to clear the caches once the module is enabled
Configure the module
-----------------------------
Once the module has been enabled, go to **Admin > Configuration > Media > File settings > Filename validation settings** and configure the validators to be used.
[ Partial fix for [#10282](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=780) ]

Create FSA filename validation module

---

docroot/sites/all/modules/custom/local/local.module
docroot/sites/all/modules/custom/siteimprove/siteimprove.module

Was previously using `hook_node_view()` to add the meta tags to the page. However, on the FSA site, this was being triggered by an embedded node that was being displayed in 'full' view mode.
Instead, use an implementation of `template_preprocess_page()` to ensure that the node is the main page one.
In addition added an implementation of `hook_siteimprove_editing_page_options_alter()` in the **local** module.
This ensures that if the SiteImprove editing page URL meta tag is present it uses the proper admin URL, not the front-end domain.
[ Partial fix for [#10289](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=787) ]

Change implementation for SiteImprove meta tags

---

docroot/sites/all/modules/custom/national_archives/national_archives.info
docroot/sites/all/modules/custom/national_archives/national_archives.module

Added handling for files to the National Archives module.
Now, whenever a file is deleted in Drupal, a redirect is put in place to the relevant National Archives URL.
Similarly, whenever a file is added, Drupal will check to see if a redirect exists for that URL, and if so, it will delete or disable the redirect.
Also:
* removed dependency on specific version of the redirect module
* cleaned up code and added some improved comments
[ Partial fix for [#2014090110000295](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=126) ]

Develop: Add file handling to national archives module

---

docroot/sites/all/modules/custom/fsa_govdelivery/fsa_govdelivery.module

When updating a taxonomy vocabulary, don't overwrite GovDelivery settings of terms.
[ Partial fix for #10225 ]

Develop: Don't overwrite existing child properties

---

docroot/sites/all/modules/custom/fsa_govdelivery/fsa_govdelivery.module
docroot/sites/all/modules/custom/govdelivery_api/govdelivery_api.admin.inc
docroot/sites/all/modules/custom/govdelivery_api/govdelivery_api.module
docroot/sites/all/modules/custom/govdelivery_api/govdelivery_api.topics.admin.inc
docroot/sites/all/modules/custom/govdelivery_api/libraries/GovDeliveryTopics.class.php
docroot/sites/all/modules/custom/govdelivery_api/theme/govdelivery-api-status-description.tpl.php

* Check API status on vocabulary and term pages
* Include a checkbox on term pages to override parent settings.
[ Partial fix for #10225 ]

Develop: Some improvements to the GovDelivery integration

---

docroot/sites/all/modules/custom/fsa_govdelivery/fsa_govdelivery.module

* Force URLs to be based on www.food.gov.uk
* Allow queue items to be returned.
[ Partial fix for #10225 ]

Use production URLs for nodes in GovDelivery

---

docroot/sites/all/modules/contrib/views_bulk_operations/actions/archive.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/book.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/delete.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/modify.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/user_cancel.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/user_roles.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions_permissions.info
docroot/sites/all/modules/contrib/views_bulk_operations/js/views_bulk_operations.js
docroot/sites/all/modules/contrib/views_bulk_operations/plugins/operation_types/action.class.php
docroot/sites/all/modules/contrib/views_bulk_operations/plugins/operation_types/rules_component.class.php
docroot/sites/all/modules/contrib/views_bulk_operations/views/views_bulk_operations_handler_field_operations.inc
docroot/sites/all/modules/contrib/views_bulk_operations/views_bulk_operations.info
docroot/sites/all/modules/contrib/views_bulk_operations/views_bulk_operations.module
docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.admin.inc
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.api.php
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.info
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.module
docroot/sites/all/modules/custom/local/local.module
docroot/sites/all/modules/custom/siteimprove/siteimprove.module

Upgraded the [Views Bulk Operations](https://www.drupal.org/project/views_bulk_operations) module to version **7.x-3.3**.
This is a security release.
Database schema updates
There are no database schema updates for this version.
Testing
-------
The functionality provided by this module is used primarily in the content administration screen in the Drupal admin interface:
https://admin.food.gov.uk/admin/content
It is also used on the Users page:
https://admin.food.gov.uk/admin/people
It provides fnctionality via the bulk update dropdown.
This should be tested once the module has been upgraded.
[ Partial fix for [#10297](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=795) ]

Develop: Upgrade Views Bulk Operations to 7.x-3.3

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

In response to the request to prevent feedback emails from spoof registration pages, added the ability to specify an array of paths for which the feedback form will not be displayed.
At present, this array is limited to pages with paths of the form `^.*/user/register$`. This will exclude paths such as:
`/news-updates/news/2011/4574/user/register`
which is one of the main culprits.
The array is currently hard-coded in the FSA Feedback module, but if necessary, a UI could be provided to allow administrators to designate other paths - though this may require regex knowledge.
Alternatively, the feedback form could be inserted using Context, by exposing it as a block. This would enable administrators to exclude it via the existing Context UI. For now though, this should suffice.
[ Partial fix …

Develop: Don't show feedback form for specified paths

---

docroot/sites/all/modules/contrib/views_bulk_operations/actions/archive.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/book.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/delete.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/modify.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/user_cancel.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions/user_roles.action.inc
docroot/sites/all/modules/contrib/views_bulk_operations/actions_permissions.info
docroot/sites/all/modules/contrib/views_bulk_operations/js/views_bulk_operations.js
docroot/sites/all/modules/contrib/views_bulk_operations/plugins/operation_types/action.class.php
docroot/sites/all/modules/contrib/views_bulk_operations/plugins/operation_types/rules_component.class.php
docroot/sites/all/modules/contrib/views_bulk_operations/views/views_bulk_operations_handler_field_operations.inc
docroot/sites/all/modules/contrib/views_bulk_operations/views_bulk_operations.info
docroot/sites/all/modules/contrib/views_bulk_operations/views_bulk_operations.module

Upgraded the [Views Bulk Operations](https://www.drupal.org/project/views_bulk_operations) module to version **7.x-3.3**.
This is a security release.
Database schema updates
There are no database schema updates for this version.
Testing
-------
The functionality provided by this module is used primarily in the content administration screen in the Drupal admin interface:
https://admin.food.gov.uk/admin/content
It is also used on the Users page:
https://admin.food.gov.uk/admin/people
It provides fnctionality via the bulk update dropdown.
This should be tested once the module has been upgraded.
[ Partial fix for [#10297](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=795) ]

Production: Upgrade Views Bulk Operations to 7.x-3.3

---

docroot/sites/all/modules/custom/national_archives/national_archives.module

When a file has been archived, we display a page indicating this and providing a link to the file on the NA site.
If the file does not exist on the NA site, we display a 404 page instead.
Also added a helper function to determine whether a path is for a file.

Develop: Add archived file interstitial page

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

In response to the request to prevent feedback emails from spoof registration pages, added the ability to specify an array of paths for which the feedback form will not be displayed.
At present, this array is limited to pages with paths of the form `^.*/user/register$`. This will exclude paths such as:
`/news-updates/news/2011/4574/user/register`
which is one of the main culprits.
The array is currently hard-coded in the FSA Feedback module, but if necessary, a UI could be provided to allow administrators to designate other paths - though this may require regex knowledge.
Alternatively, the feedback form could be inserted using Context, by exposing it as a block. This would enable administrators to exclude it via the existing Context UI. For now though, this should
suffice.
[ Partial fix …

Production: Don't show feedback form for specified paths

---

docroot/sites/all/themes/site_frontend/preprocess/page.preprocess.inc

Added some code to enable control of the output of the PageWatch delimiters via a variable.
Enabling the delimiters
------------------------------
Using Drush we can tell the delmiters to show using the following:
`drush vset fsa_govdelivery_add_pagewatch_delimiters 1`
[ Partial fix for [#10225](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=723) ]

Develop: Control output of PageWatch delimiters via variable

---

docroot/sites/all/themes/site_frontend/preprocess/page.preprocess.inc

As recommended by Richard Fong from GovDelivery, added special comments before and after the main content area to help identify genuine changes to the page.
These have initially been added to the SiteFrontend theme, as the GovDelivery modules are not currently installed on production. Once they have been deployed, these should be moved there.
The delimiters look like this:
```HTML
The content that you wish use to monitor
```
The delimiters are controlled by a Drupal variable called `fsa_govdelivery_add_pagewatch_delimiters`
Enabling the delimiters
------------------------------
Using Drush we can tell the delmiters to show using the following:
`drush vset fsa_govdelivery_add_pagewatch_delimiters 1`
[ Partial fix for [#10225](https://support.siriusopensource.com/index.pl?Action=AgentTicketZ …

Add GovDelivery content delimiters

---

docroot/sites/all/modules/custom/national_archives/includes/views_handler_archived_field.inc

If the redirect table has a status field, use this property, otherwise don't.

Check for status field in views handler

---

docroot/sites/all/themes/site_frontend/preprocess/views-view.preprocess.inc

Used an implementation of `template_preprocess_views_view()` to remove the `view-dom-id...` class from the node header fields view, which appears at the top of many nodes.
This class is used primarily with exposed filters, and is consequently not used on this view.
Because the class name changes frequently, it causes false positives for the GovDelivery HTML PageWatch mechanism.
No other views are affected.
[ Partial fix for [#10225](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=723) ]

Remove view-dom-id class for node header fields

---

docroot/sites/all/modules/contrib/current_search_links/current_search_links.info
docroot/sites/all/modules/contrib/current_search_links/plugins/item_active_links.inc

Upgraded the Current search links module to version **7.x-1.1**.
This is a security release.
Manual configuration
--------------------
Once the code has been successfully deployed, for each defined Current search block in the Drupal admin interface under:
Admin > Configuration > Search and metadata > Current search blocks
the **Search parameter** field under **Active links** needs to be updated to `keyword` instead of the default. Failure to do so will result in the links not working.
[ Partial fix for [#10112](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=610) ]

Upgrade Current search links module to version 7.x-1.1

---

docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.admin.inc
docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.module

When purging the CloudFlare cache, we now use an implementation of `hook_cron()` to retrieve items from the queue and process them in batches small enough not to exceed the CloudFlare API rate limit.
In addition, items are removed from the queue only if they have been successfully purged from CloudFlare. If not, they are released for the next cron run.
Also, the function that clears a URL from CloudFlare: `_fsa_cache_clear_cloudflare_purge_individual_url()` - now throws exceptions if purging is unsuccessful for any reason. These are then caught by the calling code and a Watchdog exception is logged, including any error message returned by CloudFlare.
Finally, we provide an administrative page that lists the items awaiting purging from CloudFlare, as well as cleaning up the admin menu a …

Develop: Improve queueing for CloudFlare cache purging

---

docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.module

Added an action and callback. Also added an implementation of `hook_file_operations()`, which is currently unused due to the fact that we're using a view for the files page.
[ Partial fix for [#10312](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=810) ]

Develop: Add file operations for clearing CloudFlare cache

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/ExternalApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.info
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/fsa_report_problem_context_condition_report_problem_node.inc

Amended functionality of the search for a local authority module so that when a node is selected to hold the block, any translations are also included.

Develop: Add translation capability for search for local authority

---

docroot/sites/all/modules/custom/fsa_report_problem/theme/local-authority-details.tpl.php

Put the text 'Email address' and 'Website' through the `t()` function in the template `local-authority-details.tpl.php` in order to make them translatable.

Make template prompts translatable

---

docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.admin.inc
docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.module

When purging the CloudFlare cache, we now use an implementation of `hook_cron()` to retrieve items from the queue and process them in batches small enough not to exceed the CloudFlare API rate limit.
In addition, items are removed from the queue only if they have been successfully purged from CloudFlare. If not, they are released for the next cron run.
Also, the function that clears a URL from CloudFlare: `_fsa_cache_clear_cloudflare_purge_individual_url()` - now throws exceptions if purging is unsuccessful for any reason. These are then caught by the calling code and a Watchdog exception is logged, including any error message returned by CloudFlare.
Finally, we provide an administrative page that lists the items awaiting purging from CloudFlare, as well as cleaning up the admin menu a …

Master: Improve queueing for CloudFlare cache purging

---

docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.admin.inc
docroot/sites/all/modules/custom/fsa_cache_clear/fsa_cache_clear.module

1. When using purge now, encode the URL
2. Don't clear the homepage when purging a file
[ Partial fix for #10312 ]

Improvements to CloudFlare cache clearing

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Modified the `hook_init()` implementation in the report a food problem module to enable any translations of the chosen node to use special path suffixes such as `<path>/postcode` and `<path>/authority`.

Enable Welsh-language version to have special paths

---

docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

We ensure that the report complete page is the correct one for the language.

Make sure report complete page is language-aware

---

docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

In postcode searches, use the local authority name stored in the database rather than the one that comes from MapIt.

Develop: Use local authority name from database for postcode

---

docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

In postcode searches, use the local authority name stored in the database rather than the one that comes from MapIt.

Use local authority name from database for postcode

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

When checking the API status, we clear the Drupal page/block caches and the Varnish cache in order to make sure that the pages get updated.
@todo Remove commented out Drupal cache clearing code if not required

Develop: Clear caches when checking API status

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

Provide some validation for postcodes prior to hitting the MapIt API. Also includes better validation error messages.
The validation mimics that which MapIt carries out, as seen here:
https://github.com/mysociety/mapit/blob/b471659b14b8912948247fa72bdbc5f65c5a6a61/mapit_gb/countries.py

Develop: Search for local authority - postcode validation

---

docroot/sites/all/modules/custom/fsa_shortcodes/fsa_shortcodes.module

As requested by Sally, iframes for embedded media now have a title attribute. By default, this will be the title supplied by the user in the `title` attribute, unless there's an `iframe_title` attribute
supplied. 
If neither is present, a generic `title` is added based on the provider name.
Also:
* Provided better attribute handling for Vimeo and YouTube
* Enabled custom error messages
* Used `filter_xss` for embed source
* Allowed SlideShare embeds
[ Partial fix for #10184 ]

Enable title attribute for media embeds

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

If there are no ratings, we don't try to display results. This avoids divide by zero errors and all kinds of other nasties.

Develop: Don't try to display results if no ratings

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/theme/rate-template-circles.tpl.php

In order for certain strings of text to appear in Welsh language, we use the `locale()` function to output the text.
Note that we do not use `t()` as these are not static strings, but variables coming from other sources beyond our control.
Note also that the translations for these strings will need to be imported since Drupal will not pick them up automatically for the most part.

Use locale() to make strings translatable

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

In order to work properly, circles.js must appear before rate.js in the JavaScript rendering order. We use an implementation of `hook_js_alter()` to reduce the weight of circles.js so that it floats above rate.js.

Develop: Change order of js files for circle ratings

---

docroot/sites/all/modules/development/module_filter/CHANGELOG.txt
docroot/sites/all/modules/development/module_filter/README.txt
docroot/sites/all/modules/development/module_filter/css/dynamic_position.css
docroot/sites/all/modules/development/module_filter/css/module_filter.css
docroot/sites/all/modules/development/module_filter/css/module_filter_tab-rtl.css
docroot/sites/all/modules/development/module_filter/css/module_filter_tab.css
docroot/sites/all/modules/development/module_filter/css/modules.css
docroot/sites/all/modules/development/module_filter/css/update_status.css
docroot/sites/all/modules/development/module_filter/js/dynamic_position.js
docroot/sites/all/modules/development/module_filter/js/module_filter.js
docroot/sites/all/modules/development/module_filter/js/module_filter_tab.js
docroot/sites/all/modules/development/module_filter/js/modules.js
docroot/sites/all/modules/development/module_filter/js/permissions.js
docroot/sites/all/modules/development/module_filter/js/update_status.js
docroot/sites/all/modules/development/module_filter/module_filter.admin.inc
docroot/sites/all/modules/development/module_filter/module_filter.info
docroot/sites/all/modules/development/module_filter/module_filter.install
docroot/sites/all/modules/development/module_filter/module_filter.module
docroot/sites/all/modules/development/module_filter/module_filter.pages.inc
docroot/sites/all/modules/development/module_filter/module_filter.theme.inc

Upgraded the Module Filter module to the latest version - **7.x-2.0**.
Database schema updates
The following database updates are required:
* 7200 - Rebuild the menu and theme registry.
* 7201 - Old update that use to remove the module_filter_dynamic_save_position variable.
Remember to run `drush updb --y` as part of the deployment process.
[ Fixes [#10337](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=835) ]

Develop: Upgrade module_filter to version 7.x-2.0

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.info
docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module
docroot/sites/all/modules/custom/fsa_social_media/fsa_social_media.module
docroot/sites/all/modules/custom/fsa_social_media/theme/block--fsa_social_media--social-media-icons.tpl.php
docroot/sites/all/themes/site_frontend/css/maintenance-page.css
docroot/sites/all/themes/site_frontend/sass/maintenance-page.scss
docroot/sites/all/themes/site_frontend/templates/system/maintenance-page.tpl.php

Created a custom site maintenance page. This involves:
* Adding a new template for the site maintenance page in the site frontend theme
* Adding new SASS/CSS files for the site maintenance page
* Adding a new custom module to enhance the maintenance mode functionality
* Making some amendments to the FSA Social media module
New module
-----------------
Once deployed, the new module will need enabling, and the caches will need clearing:
`drush en fsa_maintenance_page --y`
`drush cc all`
New URLs
--------------
The site maintenance page will be accessible here: http://dev.food.gov.uk/site-maintenance
The special CloudFlare page will be here: http://dev.food.gov.uk/site-maintenance/cf
@todo Use the CloudFlare API to reflect changes to the error page

Develop: Create custom site maintenance page

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module
docroot/sites/all/themes/site_frontend/css/maintenance-page.css
docroot/sites/all/themes/site_frontend/sass/maintenance-page.scss

Added the ability to embed a Twitter widget in the site maintenance page, configured via the admin interface.

Develop: Allow Twitter widget to be embedded in maintenance page

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module

It's now possible to configure CloudFlare error page from within the maintenance mode admin page.

Develop: Add CloudFlare config to maintenance page admin

---

docroot/sites/all/themes/site_frontend/css/ie/ie8.css
docroot/sites/all/themes/site_frontend/css/site-frontend.no-query.css
docroot/sites/all/themes/site_frontend/css/site-frontend.styles.css
docroot/sites/all/themes/site_frontend/sass/components/_carousel.scss
docroot/sites/all/themes/site_frontend/sass/ie/ie8.scss

* Changed width for homepage carousel text box from fixed (400px) to automatic
* For IE8 browser, set image width in carousel to `inherit`
[ Fixes #10345 ]

Amend styling for carousel text box

---

docroot/sites/all/modules/features/base/ckeditor___editor/ckeditor___editor.features.ckeditor_profile.inc
docroot/sites/all/modules/features/base/ckeditor___editor/ckeditor___editor.features.user_permission.inc

Updated the configuration for the CKEditor WYSIWYG editor within the feature CKEditor.
* Removed permission for the **About us** role as it no longer exists
* Removed the insert media button as it no longer works with the latest version of the module
[ Partial fix for #1084 ]

Update CKEditor feature

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

When making AHAH calls, the rating widget provided by the contrib Rate module was not taking into account the current page language, so the response was always returned in English.
1. Created a new callback function to set language based on URL before calling the existing function
2. Added a `hook_menu_alter()` implementation to substitute our new callback for the existing callback used when making AHAH calls
3. Modified the base path used in AHAH calls by the Rate module to include the page's language code
[ Partial fix for #10346 ]

Develop: Handle Welsh language AHAH calls for Rate widget

---

docroot/sites/all/modules/contrib/hierarchical_select/hierarchical_select.info
docroot/sites/all/modules/contrib/hierarchical_select/hierarchical_select.module
docroot/sites/all/modules/patches/PATCHED.txt
docroot/sites/all/modules/patches/hierarchical_select-require_jquery_ui-2656040-1.patch

Due to the JQuery UI library not always being loaded, the hierarchical select module was not working properly on file edit pages.
This has been patched on Drupal.org - issue #2656040.
https://www.drupal.org/node/2656040
The patch has been applied to this branch.
[ Fixes #10336 ]

Patch the Hierarchical select module

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

For default text entries in the report a food problem module, change the variable names so they match the existing text entries - ie drop the `_default_` prefix.

Change variable name for default text entries

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/report_complete_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Local authority names are now translated on the make report and report complete stages.
Also check that text entry values are not empty when returning `FsaReportProblemTextEntry` objects.
[ Partial fix for #10351 and #10352 ]

Translate local authority names

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

The old manual report URL was /enforcement/report-problem/manual.
This has now changed to:
/enforcement/report-problem/report/manual
We therefore include a `drupal_goto()` implementation in the block content generator just in case anyone uses the old URL.

Handle old manual report entry URL

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Changed labels for email address field in report a food problem admin interface to 'Report a food problem email address', as requested by Sally.

Develop: Tweak email address labels

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Added a query suffix field to help restrict Google Places search results to UK establishments only, thereby ensuring that searches without locations, such as 'pizza hut' and those with ambiguous locations such as 'pizza hut bristol' (there are Bristols in other countries) return results.
[ Fixes #10356 ]

Develop: fix problem with Google Places search results

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.install
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Added an additional helper function to provide text entries for the search for local authority service.

Develop: Add text specific to search for local authority

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/business_results_form.php

For the report a food problem block, the verb on the button should be 'Report', but for all other situations, it should be 'Choose'.
Set this based on block `$delta`.

Develop: Change button verb based on block $delta

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

The local authority contact details are now added to the acknowledgement emails via a new token that can be entered via the Drupal admin user interface.
The new token is: `[local_authority:contact_statement]`

Develop: Add local authority contact to email via tokens

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/postcode_search_form.php

Previously this wasn't set and was causing a notice to be generated.

Set $delta in postcode validation callback

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

Use proper header configuration and add `tablesort` to the `EntityFieldQuery` that returns the list of submitted reports. The table within the admin interface is now properly sortable.

Develop: Make problem report table properly sortable

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/theme/problem-report.tpl.php

* On report listing page, show date report submitted
* On report listing page, shorten date format for problem date
* On report listing page, change column headings to reflect the different dates
* On report listing page, truncate the business name to make better use of space
* On report detail page, don't display reporter details item if no name or email provided

Develop: improve display of food problem reports

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

When attempting to view a food problem report, if the specified report does not exist or there are no reports in the system, we return an error message to the user with a link to the report listing page.

Develop: Return error message if report not found

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

Removed the report date column from the food problem reports listing table as requested by Sally. Also update the column header of the submitted date.

Develop: Remove report date column from listing

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Previously, only the name and FHRS email address were being updated from FHRS data on the daily local authority update. Added the URL to this as requested by Sally.

Develop: Update local authority FHRS URL on cron

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Previously, only the name and FHRS email address were being updated from FHRS data on the daily local authority update. Added the URL to this as requested by Sally.

Update local authority FHRS URL on cron

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Ensure that the **From** and **Sender** headers are the same for outgoing emails sent by the report a food problem module.

Develop: Set From and Sender headers for outgoing emails

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

We now remove reporter details (name and email address) from any sent food problem reports.
This is done on cron.
We also hide the reporter details from the Drupal admin interface.
[ Partial fix for #10374 ]

Develop: Remove reporter details from sent reports

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

Whether or not the reporter name and email fields are mandatory can now be set via the admin UI.
[ Partial fix for #10374 ]

Develop: enable administrator to control required status of reporter details fields

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

This reverts commit 0365fecf321bbdd205aa531692f26c33251f9a91.
This may be causing issues with emails being delivered to FSA.
Further investigation is required before re-enabling this.

Develop: Revert "Set From and Sender headers for outgoing emails"

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

* We no longer display reporter details on food problem reports
* Once a report has been sent, a cron job will delete the reporter details but retain the rest of the report data
* The mandatory status of the reporter details fields can now be controlled via the admin UI
[ Partial fix for #10374 ]

Don't show reporter details on food problem reports

---

docroot/sites/all/modules/custom/fsa_email_test/fsa_email_test.module

Otherwise we end up with two headers.
[ Partial fix for #10383 ]

Develop: Change Return-path to Return-Path

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

In the Report a food problem module, we no longer set the `Reply-to` header for the emails generated when a report is submitted as this appears to be preventing delivery via MessageLabs.
[ Partial fix for #10383 ]

Develop: Don't set return-path header in RAFP

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

This reverts commit 375a91c2cfa56a820257d4a30d94b4df7ae8fbb8.
Reinstating the `sender` header as this doesn't appear to be causing the delivery problem with MessageLabs.
[ Partial fix for #10383 ]

Develop: Reinstate Sender headers

---

docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.admin.inc
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.inc
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.install
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.module

Modified the existing FSA Language negotiation module to enable admin users with the correct permission to specify that paths that Drupal will consider to be Welsh.
By default, the current settings are retained.
[ Partial fix for #10395 ]

Develop: Allow administrators to specify Welsh language paths

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

We allow users with the permission `view food problem reports` to access these reports without being given permission to view the entire Reports section.
This is achieved using a duplicate menu item that is hidden from those who have access to the report section to avoid duplication.
[ Partial fix for #10393 ]

Develop: Allow access to food problem reports for non-administrators

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

We allow users with the permission `view food problem reports` to access these reports without being given permission to view the entire Reports section.
This is achieved using a duplicate menu item that is hidden from those who have access to the report section to avoid duplication.
[ Partial fix for #10393 ]

Master: Allow access to food problem reports for non-administrators 

---

docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.admin.inc
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.inc
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.install
docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.module

Modified the existing FSA Language negotiation module to enable admin users with the correct permission to specify the paths that Drupal will consider to be Welsh.
By default, the current settings are retained, and the new path `wales/wales` is added.
[ Partial fix for #10395 ]

Master: Allow administrators to specify Welsh language paths

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Hid the problem time field on the form and in the admin system. Also in the emails.
[ Fixes #10400 ]

Master: Hide time field on report a food problem

---

docroot/sites/all/modules/custom/fsa_report_problem/views/local_authority_details.view

Changed to a menu tab and set weight to 30.
[ Partial fix for #10405 ]

Develop: Change menu item type and weight for local authorities

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

The option labels for the views exposed filters for manual submission and email sent are set to 'True' and 'False' by default.
To tie in better with the values used in the table, we want them to be 'Yes' and 'No' respectively.
As this isn't provided by the views filter handler, rather than creating a new handler, we use an implementation of `hook_form_FORM_ID_alter()` to replace the filter options instead.
[ Partial fix for #10405 ]

Develop: Modify option labels in problem reports view

---

docroot/sites/all/modules/custom/fsa_report_problem/views/local_authority_details.view

For some reason, the view for local authority details had lost its menu setting. Added it back in.
[ Partial fix for #10405 ]

Change menu setting for local authority view

---

docroot/sites/all/modules/custom/fsa_revisioning/README.txt
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.info
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.install
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.module
docroot/sites/all/modules/custom/fsa_revisioning/js/fsa-revision-schedule.js

Created a new custom module to supplement and improve some of the functionality provided by the contributed Revisioning and Revisioning Scheduler modules.
Enhancements include:
1. A fix for a bug whereby scheduled publication dates aren't always saved the
first time they're added. This bug has been reported on Drupal.org:
https://www.drupal.org/node/2445469. Although a patch has been provided, it
was deemed easier for the upgrade path if we fixed it in this custom module.
The fix involves adding an update hook that sets the weight of the
revisioning_scheduler module as greater than the revisioning module.
2. Use a date popup field when setting publication dates. If the Date API
module is available, we replace the standard text field for publication date
with a more user-friendly calendar …

Develop: Create new custom revisioning module

---

docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.install

In the FSA revisioning module, we need to ensure that the update hooks are run when the module is installed.
We therefore add an implementation of `hook_install()` and use this to set the schema_version to **7000**. This should result in updates **7001** and **7002** running immediately following the module being enabled.
[ Partial fix for #10354 ]

Develop: Add install hook to make update hooks run

---

docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.install

Name of install hook was wrong, so it didn't get called.
[ Partial fix for #10354 ]

Develop: Fix typo in function name

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.info
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.install
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module
docroot/sites/all/modules/custom/fsa_guid/views/fsa_guid.views.inc
docroot/sites/all/modules/custom/fsa_guid/views/handlers/fsa_guid_views_handler_field_guid.inc

Created a new custom module to provide special GUIDs that can be updated as required.
Module to enable
Once the code is deployed, the new module needs to be enabled:
`drush en fsa_guid --y`
Then clear the caches:
`drush cc all`
[ Partial fix for #10357 ]

Develop: Create FSA GUID module

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.admin.inc
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module

* We now allow global tokens such as site name within the GUID
* Node URL is now available as a token for use in the GUID
[ Partial fix for #10357 ]

Develop: Allow additional tokens in FSA GUIDs

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.admin.inc
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.info
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.install
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module
docroot/sites/all/modules/custom/fsa_guid/views/fsa_guid.views.inc
docroot/sites/all/modules/custom/fsa_guid/views/handlers/fsa_guid_views_handler_field_guid.inc
docroot/sites/all/modules/custom/fsa_guid/views/plugins/fsa_guid_views_plugin_row_node_rss.inc

Created a new custom module to provide special GUIDs that can be updated as required.
Module to enable
Once the code is deployed, the new module needs to be enabled:
`drush en fsa_guid --y`
Then clear the caches:
`drush cc all`
[ Partial fix for #10357 ]

Master: Create new FSA GUID module

---

docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.module

If the publication date field is populated for a given revision, the revision_operation radio button should be set to the third option, otherwise the publication date field is hidden.
[ Partial fix for #10354 ]

Develop: Set correct revision option if date populated

---

docroot/sites/all/modules/development/stage_file_proxy/INSTALL.txt
docroot/sites/all/modules/development/stage_file_proxy/stage_file_proxy.info
docroot/sites/all/modules/development/stage_file_proxy/stage_file_proxy.module

Upgraded the stage file proxy module to version 7.x-1.7.
Note that this module is used only on local development sites and is not enabled on any FSA environment.
[ Fixes #10481 ]

Master: Upgrade stage file proxy to version 7.x-1.7

---

docroot/sites/all/modules/custom/fsa_revisioning/README.txt
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.info
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.install
docroot/sites/all/modules/custom/fsa_revisioning/fsa_revisioning.module
docroot/sites/all/modules/custom/fsa_revisioning/js/fsa-revision-schedule.js

Master: Fix/10354 auto signoff in drupal
Ticket: 10354 
Create new custom revisioning module
Created a new custom module to supplement and improve some of the functionality provided by the contributed Revisioning and Revisioning Scheduler modules.
Enhancements include:
1. A fix for a bug whereby scheduled publication dates aren't always saved the
first time they're added. This bug has been reported on Drupal.org:
https://www.drupal.org/node/2445469. Although a patch has been provided, it
was deemed easier for the upgrade path if we fixed it in this custom module.
The fix involves adding an update hook that sets the weight of the
revisioning_scheduler module as greater than the revisioning module.
2. Use a date popup field when setting publication dates. If the Date API
module is …

Master: Fix/10354 auto signoff in drupal

---

docroot/sites/all/modules/custom/FSA_language_negotiation/FSA_language_negotiation.module

To enable admin users to enter translations containing code that would otherwise be considered dangerous, such as `<div>` elements, we create a new permission and replace the standard validation function for the string translation form.
If the user is User 1, then validation is bypassed. Similarly, if the user has the new permission, validation is bypassed. For all other users, the standard validation function is used.
[ Partial fix for #10781 ]

Master: Allow bypassing of translation validation for admin users

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.admin.inc
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module

When editing the GUID pattern for RSS feeds, invalid tokens, including those defined by other modules, can no longer be entered.
[ Partial fix for #10866 ]

Develop: Add additional validation for GUID pattern form

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.admin.inc
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module

In order to avoid issues with tokens not being replaced properly in RSS GUIDs, we now use an alternative token replacement function to Drupal's built-in token API.
[ Fixes #10866 ]

Master: Don't use Drupal token API in GUIDs

---

docroot/sites/all/modules/custom/fsa_guid/views/handlers/fsa_guid_views_handler_field_guid.inc

In the Views handler, we make sure that the `$nid` variable is populated to avoid errors in generating the GUID.
[ Fixes #101064 ]

Ensure that $nid is populated

---

docroot/sites/all/modules/custom/commitees_custom/commitees_custom.install
docroot/sites/all/modules/custom/commitees_custom/commitees_custom.module

Created a new role to provide easy access for users to all committees (organic groups).
When users are assigned this role, they are automatically granted membership of all organic groups. This enables them to edit content created within these groups.
When this role is removed from a user account, ALL committee (organic group) memberships are also removed for this user.
When new groups are added, membership is automatically assigned to users with the all community role.
In order for the new role to be created, the database schema needs updating:
``drush updb --y``
[ Partial fix for #10506 ]

10506: Enable role-based all committee access (develop)

---

docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.features.inc
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.info
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.module
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.views_default.inc

In order to allow editors to add unpublished pages to the Child pages section of a content item, a modification was required to the entity reference view that generates the list of pages.
Previously it would return only published pages. This restriction has now been removed.
This view and the other entity reference widget views have now been added to a new feature called `entity_reference_views_feature`.
This module will need to be enabled on the server for this to work:
``drush en entity_reference_views_feature --y``
The feature should then be reverted:
``drush fr entity_reference_views_feature --y``
[ Partial fix for #10861 ]

10861: Linking to unpublished pages (develop)

---

docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.features.inc
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.info
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.module
docroot/sites/all/modules/features/global/entity_reference_views_feature/entity_reference_views_feature.views_default.inc

In order to allow editors to add unpublished pages to the Child pages section of a content item, a modification was required to the entity reference view that generates the list of pages.
Previously it would return only published pages. This restriction has now been removed.
This view and the other entity reference widget views have now been added to a new feature called `entity_reference_views_feature`.
This module will need to be enabled on the server for this to work:
``drush en entity_reference_views_feature --y``
The feature should then be reverted:
``drush fr entity_reference_views_feature --y``
[ Partial fix for #10861 ]

10861: Linking to unpublished pages (master)

---

docroot/sites/all/modules/custom/commitees_custom/commitees_custom.module

When removing group memberships from users who are having the All committee memberhip role taken away, don't remove those for which the user is the manager.
[ Partial fix for #10506 ]

10506: Don't remove manager from groups.

---

docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module
docroot/sites/all/modules/custom/local/local.module

We now clear committee-based URLs for files and pages from CloudFlare.

10421: Clear committee URLs from CloudFlare (develop)

---

docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_image.module

* Avoid multiple calls when clearing files
* URLencode paths to be cleared

10421: Amend CloudFlare cache clear functionality (develop)

---

docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module

When encoding CloudFlare URLs, use `drupal_encode_path()` instead of `urlencode()`.

10421: Use drupal_encode_path(), not urlencode() (develop)

---

docroot/sites/all/modules/contrib/httprl/LICENSE.txt
docroot/sites/all/modules/contrib/httprl/README.txt
docroot/sites/all/modules/contrib/httprl/examples/httprl.examples.php
docroot/sites/all/modules/contrib/httprl/httprl.admin.inc
docroot/sites/all/modules/contrib/httprl/httprl.async.inc
docroot/sites/all/modules/contrib/httprl/httprl.info
docroot/sites/all/modules/contrib/httprl/httprl.install
docroot/sites/all/modules/contrib/httprl/httprl.module
docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.admin.inc
docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.info
docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.install
docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_image.info
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_image.module
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_ui.admin.inc
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_ui.info
docroot/sites/all/modules/custom/cloudflare_cache_clear/modules/cloudflare_cache_clear_ui.module
docroot/sites/all/modules/custom/local/local.module

Created a new cache clearing module to allow clearing of items from the CloudFlare cache using the latest version of the CloudFlare API.
Also included is the HTTPRL module for making parallel, non-blocking HTTP requests.
----------------------
Once the code has been deployed, the new module will need to be enabled:
```
drush en cloudflare_cache_clear --y
drush en cloudflare_cache_clear_ui --y
drush en cloudflare_cache_clear_image --y
```
It would also be good to clear the Drupal caches:
`drush cc all `

10421: Upgrade CloudFlare cache clearing to version 4

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Added the ability to include the MapIt API key when making requests as part of the Report a food problem service.
Manual configuration
The MapIt API key needs to be added in the configuration interface in Drupal via:
Admin > Configuration > Food problem reporting > API settings
Note that it needs to be added for each service.
The API key can be found in LastPass under MapIt
[ Partial fix for #101415 ]

101415: Use MapIt API key (develop)

---

docroot/sites/all/modules/features/global/sitewide_feature/sitewide_feature.module

By default, Entity reference fields will not allow unpublished nodes to be included. If an unpublished node is added, a validation handler will prevent the node edit form from submitting.
To get around this, we implement a query tag alter hook and remove the condition that requires the node to be published.
[ Partial fix for #102052 ]

102052: Allow unpublished nodes in ref fields (master)

---

docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module

Menu links are causing problems when clearing from CloudFlare due to the fact that they are neither entities nor objects. This causes an exception to be thrown.
We therefore catch any exceptions.
[ Partial fix for #102408 and #102392 ]

102408: Fix issue with menu links in CloudFlare cache clear

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Added the ability to include the MapIt API key when making requests as part of the Report a food problem service.
Manual configuration
The MapIt API key needs to be added in the configuration interface in Drupal via:
Admin > Configuration > Food problem reporting > API settings
Note that it needs to be added for each service.
The API key can be found in LastPass under MapIt
[ Partial fix for #101415 ]

101415: Use MapIt API key (master)

---

docroot/sites/all/modules/custom/cloudflare_cache_clear/cloudflare_cache_clear.module

Due to a bug in the CloudFlare cache clear module, some menu links weren't appearing as options when selecting parents.
Fixed the bug.
[ Partial fix for 102408 and 102392 ]

102408 Fix broken menu links

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.install

We use an update hook to ensure the Mollom module is installed and enabled before creating the mollom settings for the feedback form.
[ Partial fix for 103273 ]

103273: Enable Mollom module in update hook (develop)

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.install
docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module

Added a new validation for the feedback form that checks to see if both fields contain the same information. If so, we warn the user as it is likely spam.
[ Partial fix for 103273 ]

103273: Add extra validation to compare feedback fields (develop)

---

docroot/sites/all/modules/custom/commitees_custom/commitees_custom.install
docroot/sites/all/modules/custom/commitees_custom/commitees_custom.module

Added functions to create taxonomy terms in the file_tags vocabulary for new and existing committee items. Added a database update hook to run it.
[ Partial fix for 103497 ]

103497: Create file tags for committee nodes

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc

In order to ensure that the correct MapIt API key is included in requests, we provide a delta wherever we call the API function.
[ Partial fix for 103798 ]

103798: Make sure MapIt API key is supplied

---

docroot/sites/all/modules/features/global/sitewide_feature/sitewide_feature.module

For external link content items and for redirects, we replace any instances of the old National Archives base URL with the new version.
[ Partial fix for 104082 ]

104082: Replace National Archives URL

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

For forwarded food problem reports, we set the Return-Path header to be the same as the From address to prevent bouncebacks from Office 365.
[ Partial fix for 104248 ]

104248 Set Return-Path header for forwarded food problem reports

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

For forwarded food problem reports, we set the Return-Path header to be the same as the From address to prevent bouncebacks from Office 365.
[ Partial fix for 104248 ]

104248: Set Return-Path for forwarded food problem reports

---

docroot/sites/default/settings.php

Increased the PHP `memory_limit` setting from 700M to 900M when in the
admin section of the site.
[ Partial fix for #104870 ]

104248: Increase admin memory limit (develop)

---

docroot/sites/default/settings.php

Increased the PHP `memory_limit` setting from 700M to 900M when in the admin section of the site.
[ Partial fix for #104870 ]

104870: Increase admin memory to 900M

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Added a new custom header - `X-Reporter` - to the report emails generated by the report a food problem module. This will allow emails to be dropped by Postfix based on the reporter's email address.
[ Partial fix for 104904 ]

104903: Add X-Reporter header to RAFP emails

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

In the new custom `X-Reporter` email header, we now use the actual reporter email address (if supplied), rather than the sender address.
[ Partial fix for 104903 ]

104903: Use reporter email in X-Reporter header

---

docroot/sites/all/themes/committee_acss/committee_acss.info

Added a couple of new domains for the ACSS committee site for use with the dev and staging environments:
* acss.dev.food.gov.uk
* acss.staging.food.gov.uk
[ Partial fix for 105127 ]

105127: Add new ACSS domains for dev and staging

---

docroot/sites/all/modules/custom/fsa_beta_banner/fsa_beta_banner.module

Added `rel="noopener noreferrer"` to beta site link to prevent potential phishing attacks.
[ Partial fix for 105041 ]

105041: Add noopener noreferrer to beta link

---

docroot/sites/all/modules/custom/fsa_beta_banner/fsa_beta_banner.module
docroot/sites/all/modules/custom/fsa_beta_banner/theme/block--fsa-beta-banner.tpl.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.install
docroot/sites/all/modules/features/global/sitewide_feature/sitewide_feature.install

It is now possible to enable/disable the beta banner and to change the text and link URL for the beta banner via the block configure interface in the Drupal admin UI.
The beta banner is also now disabled by default.
[ Partial fix for 105041 ]

105041: Allow beta banner configuration via Drupal admin UI

---

docroot/sites/all/modules/custom/local/local.module

Added the correct path and subdomain for the ACSS committee site.
[ Partial fix for 105127 ]

105127: Add ACSS path to committee domains

---

docroot/sites/all/modules/custom/local/local.module

Updating the custom 'local' module so it sees old.food.gov.uk as the site's default domain, now that www.food.gov.uk is used by a separate D8 site. Hopefully this will fix the ajax path issue, or at least point it to the same site.

Update references to old domain from www. to old.

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.install

Remove the feedback form from Mollom config as part of a module update.

Remove feedback form from Mollom config
