FoodStandardsAgency/food-gov-uk

docroot/sites/all/modules/contrib/crazyegg/LICENSE.txt
docroot/sites/all/modules/contrib/crazyegg/README.txt
docroot/sites/all/modules/contrib/crazyegg/crazyegg.info
docroot/sites/all/modules/contrib/crazyegg/crazyegg.module
docroot/sites/all/modules/contrib/crazyegg/includes/admin.inc
docroot/sites/all/modules/patches/FSA-10248-crazyegg-add-cache-breaker.patch
docroot/sites/all/modules/patches/FSA-10248-crazyegg-update-javascript-host.patch
docroot/sites/all/modules/patches/FSA-10248-enable-choice-of-code-rendering.patch
docroot/sites/all/modules/patches/PATCHED.txt

Installed a patched version of the contrib CrazyEgg module: 7.x-1.0
The module has been patched as follows:
1. The cache-breaking code has been added to the JavaScript link
2. The JavaScript host has been updated
3. A new option has been to the admin interface to enable administrators to choose where the JavaScript should be rendered - header or footer
All patches are stored in the patches folder.
[ Partial fix for #10248 ]

Develop: Install CrazyEgg module

---

docroot/sites/all/modules/custom/national_archives/national_archives.module

Added an implementation of `hook_action_info()` to provide actions for use with VBO and elsewhere.

Add action info to National Archives module

---

docroot/sites/all/modules/custom/national_archives/national_archives.module

Added a new VBO action callback function for creating National
Archives redirects.

Create VBO action to create redirects

---

docroot/sites/all/modules/custom/national_archives/national_archives.module

Added a new action callback for disabling National Archives redirects.
Also fixed an issue with the path in the create redirect action.

Add action for disabling NA redirects

---

docroot/sites/all/modules/custom/national_archives/includes/views_handler_archived_field.inc
docroot/sites/all/modules/custom/national_archives/national_archives.info
docroot/sites/all/modules/custom/national_archives/national_archives.module
docroot/sites/all/modules/custom/national_archives/national_archives.views.inc

Added a custom field handler to display whether a page has been 'archived' to the National Archives.

Add some views integration

---

docroot/sites/all/modules/custom/national_archives/includes/views_handler_archived_field.inc

Check status of NA redirects

---

docroot/sites/all/modules/contrib/encryptfapi/LICENSE.txt
docroot/sites/all/modules/contrib/encryptfapi/encryptfapi.info
docroot/sites/all/modules/contrib/encryptfapi/encryptfapi.module
docroot/sites/all/modules/contrib/encryptfapi/encryptfapi.test
docroot/sites/all/modules/contrib/encryptfapi/help/encryptfapi.help.ini
docroot/sites/all/modules/contrib/encryptfapi/help/usage.html
docroot/sites/all/modules/contrib/encryptfapi/tests/encryptfapi_test.info
docroot/sites/all/modules/contrib/encryptfapi/tests/encryptfapi_test.module

This module works with the Encrypt module to provide integration with the Drupal form API. It enables us
easily to encrypt Form API elements.
https://www.drupal.org/project/encryptfapi
Version: 7.x-2.0-beta1

Install Encrypt FAPI module - version 7.x-2.0-beta1

---

docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.admin.inc
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.api.php
docroot/sites/all/modules/custom/fsa_filename_validation/fsa_filename_validation.module

* Added additional hooks (documented in API file)
* Added some useful helper functions
* Improved commenting
* Fixed some whitespace errors
[ Partial fix for #10282 ]

Develop: Various enhancements to filename validation module

---

docroot/sites/all/modules/custom/fsa_search_spellcheck/fsa_search_spellcheck.module

Left some old views code in place.
[ Partial fix for #10176 ]

Fix coding bug

---

docroot/sites/all/modules/custom/national_archives/national_archives.admin.inc
docroot/sites/all/modules/custom/national_archives/national_archives.module
docroot/sites/all/modules/custom/national_archives/theme/national-archives-archived-file.tpl.php

* Enable the disclaimer to be set via the admin UI
* If a redirect previously existed for a file, save it and recreate it later

Develop: Improve file archive page handling and recreate redirects

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Some improvements to local authority import for report a food problem:
* Include `COI` authority type for Isles of Scilly
* Include mappings array to make import easier
* Check that we have local authorities before looping through them for display

Develop: Improve local authority import

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.install
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.variable.inc
docroot/sites/all/modules/custom/fsa_report_problem/text/contact_local_authority.cy.txt
docroot/sites/all/modules/custom/fsa_report_problem/text/find_business_intro.cy.txt
docroot/sites/all/modules/custom/fsa_report_problem/text/make_report_intro.cy.txt
docroot/sites/all/modules/custom/fsa_report_problem/text/report_complete.cy.txt

Added various improvements to the Welsh language handling, including:
* Initial setup of variables to be multilingual
* Enable importing of Welsh-language files
* Added missing variables to variable.inc
Improved the admin interface to allow creation of local authorities

Welsh language fixes and admin functions

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

* Ensure that data capture status saved from block configure screen
* Add business location to aria label on select this business buttons on results screen

Develop: Enhancements to report food problem

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

Paths to the start page now take into account both English and Welsh-language versions.

Better path handling in search for local authority

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/ExternalApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/GooglePlacesApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/GooglePlacesApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.info
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Various improvements to the way in which the report a problem module handles API status.

Improvements to API status handling

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/ExternalApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/GooglePlacesApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.info
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc
docroot/sites/all/modules/custom/fsa_report_problem/theme/external-api-status.tpl.php

Improve external API exception handling for the search for local authority module.
Also enable custom user agent for MapIt to allow tracking of usage.

Develop: Search for local authority - exception handling

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc
docroot/sites/all/modules/custom/fsa_report_problem/theme/external-api-status.tpl.php

* Add translation for local authority names
* Enable editing of local authority names
* Test for existence of API status variable before trying to render status

Develop: Search for local authority - translation

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/ExternalApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/GooglePlacesApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/GooglePlacesApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiStatus.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.info
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc
docroot/sites/all/modules/custom/fsa_report_problem/theme/external-api-status.tpl.php

API Status
--------------
* Exception handling for external APIs built in
* API status displayed in admin interface
* API availability determines service availability
MapIt enhancements
-----------------------------
* MapIt URL can be edited
* MapIt authority types can be set via the admin UI
* MapIt user agent string can be set via the admin UI
Welsh Language
* Local authority names editable
* Local authority names translated on display

Search for local authority - API status and language enhancements

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

Were previously hard coded. Now editable.

Develop: Get postcode error messages from text entries

---

docroot/sites/all/modules/custom/fsa_report_problem/classes/MapItApiException.class.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc

Added local validation of postcodes to the search for local authority service.

Improved postcode validation - search for local authority

---

docroot/sites/all/modules/custom/fsa_shortcodes/fsa_shortcodes.module

Some amendments to the FSA shortcodes module:
* Removed DailyMotion provider
* Sanitised variables prior to output
* Add provider names via hook
* Add tips callbacks
[ Partial fix for #10184 ]

Amendments to FSA Shortcodes module

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Used `hook_form_FORM_ID_alter()` to add some additional options to the anonymous voting window select menu for 10 seconds, 30 seconds and 1 minute.

Add additional options for anonymous voting window

---

docroot/sites/all/modules/development/module_filter/CHANGELOG.txt
docroot/sites/all/modules/development/module_filter/README.txt
docroot/sites/all/modules/development/module_filter/css/dynamic_position.css
docroot/sites/all/modules/development/module_filter/css/module_filter.css
docroot/sites/all/modules/development/module_filter/css/module_filter_tab-rtl.css
docroot/sites/all/modules/development/module_filter/css/module_filter_tab.css
docroot/sites/all/modules/development/module_filter/css/modules.css
docroot/sites/all/modules/development/module_filter/css/update_status.css
docroot/sites/all/modules/development/module_filter/js/dynamic_position.js
docroot/sites/all/modules/development/module_filter/js/module_filter.js
docroot/sites/all/modules/development/module_filter/js/module_filter_tab.js
docroot/sites/all/modules/development/module_filter/js/modules.js
docroot/sites/all/modules/development/module_filter/js/permissions.js
docroot/sites/all/modules/development/module_filter/js/update_status.js
docroot/sites/all/modules/development/module_filter/module_filter.admin.inc
docroot/sites/all/modules/development/module_filter/module_filter.info
docroot/sites/all/modules/development/module_filter/module_filter.install
docroot/sites/all/modules/development/module_filter/module_filter.module
docroot/sites/all/modules/development/module_filter/module_filter.pages.inc
docroot/sites/all/modules/development/module_filter/module_filter.theme.inc

Upgraded the Module Filter module to the latest version.
Database schema updates
The following database updates are required:
* 7200 - Rebuild the menu and theme registry.
* 7201 - Old update that use to remove the module_filter_dynamic_save_position variable.
Remember to run `drush updb --y` as part of the deployment process.
[ Fixes [#10337](https://support.siriusopensource.com/index.pl?Action=AgentTicketZoom;TicketID=835) ]

Upgrade module_filter to version 7.x-2.0

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

It is now possible to export overall rating data for the report a food problem/search for local authority service.

Develop: Add rating data export function

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module
docroot/sites/all/themes/site_frontend/css/maintenance-page.css
docroot/sites/all/themes/site_frontend/sass/maintenance-page.scss

* Hide CloudFlare error message
* Update CloudFlare error page when maintenance page updated

Develop: Improve maintenance page functionality

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module

Use site domain, not force to dev

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module
docroot/sites/all/themes/site_frontend/css/maintenance-page.css
docroot/sites/all/themes/site_frontend/sass/maintenance-page.scss

Develop: Maintenance page tweaks

---

docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.info
docroot/sites/all/modules/custom/fsa_maintenance_page/fsa_maintenance_page.module
docroot/sites/all/modules/custom/fsa_social_media/fsa_social_media.module
docroot/sites/all/modules/custom/fsa_social_media/theme/block--fsa_social_media--social-media-icons.tpl.php
docroot/sites/all/themes/site_frontend/css/maintenance-page.css
docroot/sites/all/themes/site_frontend/sass/maintenance-page.scss
docroot/sites/all/themes/site_frontend/templates/system/maintenance-page.tpl.php

A new FSA maintenance page module is being deployed.

Enable new maintenance mode page

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/business_lookup_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/business_results_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/make_report_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/postcode_search_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/report_complete_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/includes/form.inc
docroot/sites/all/modules/custom/fsa_report_problem/theme/report-problem-block-content.tpl.php

This is the first test iteration of the new URL structure for the report a food problem service.
[ Partial fix for #10349 ]

Develop: Implement new URL structure for report a food problem

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Modified to prevent duplicate IDs
[ Partial fix for #10349 ]

Develop: Modify code for adding rating widget

---

docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.admin.inc
docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.info
docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.module

A few little bug fixes and enhancements.

Develop: Amendments to the SurveyMonkey module

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/business_lookup_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/business_results_form.php
docroot/sites/all/modules/custom/fsa_report_problem/forms/postcode_search_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/theme/report-problem-block-content.tpl.php

API settings can now be configured on a per-service basis where appropriate.

Develop: Modify API settings for report food problem

---

docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.admin.inc
docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.info
docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.install
docroot/sites/all/modules/custom/fsa_survey_monkey/fsa_survey_monkey.module

Created a new survey module to enable surveys (in the first instance from SurveyMonkey) to be added to specified pages on the site.
[ Partial fix for #10355 ]

Add new survey module

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.install
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

* Added an update hook to initialise variables
* Added a parameter to prevent variables being reset

Develop: Enable translations of new text variables

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

A few small amends to find a food safety team

Develop: Find food safety team amends

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

* Remove rating widget from find a food safety officer service
* Add rating widget to report a food problem service
[ Partial fix for #10352 and #10351 ]

Develop: rating widget amendments

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/business_results_form.php

Develop: Make text entries on business listing form block-specific

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

* Added a reply-to field for emails
* Added a checkbox to include email dev message
* Removed 'TEST' from email subject
[ Partial fix for #10352 and #10351 ]

Develop: Add reply-to field for emails etc

---

docroot/sites/all/modules/custom/fsa_report_problem/forms/postcode_search_form.php
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.install
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Create getPlain() method and use it for field labels

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.admin.inc
docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module
docroot/sites/all/modules/custom/fsa_report_problem/theme/problem-report.tpl.php

Various amendments to the display of food problem reports within the Drupal admin section.

Amend display of food problem reports in admin

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Changed the token replacement so that the date format changes based on whether we're capturing problem time or not.
[ Partial fix for #10400 ]

Develop: Change date format in emails

---

docroot/googlece4ec59c1cf1c799.html

Added file googlece4ec59c1cf1c799.html as supplied by Tatiana via the ticket.
[ Partial fix for #10402 ]

Develop: Add YouTube verification file

---

docroot/googlece4ec59c1cf1c799.html

Added file googlece4ec59c1cf1c799.html as supplied by Tatiana via the ticket.
[ Partial fix for #10402 ]

Master: Add YouTube verification file

---

docroot/sites/all/modules/custom/fsa_report_problem/fsa_report_problem.module

Develop: Modify filename and MIME type of RAFP exports

---

docroot/sites/all/modules/custom/fsa_guid/fsa_guid.admin.inc
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.info
docroot/sites/all/modules/custom/fsa_guid/fsa_guid.module
docroot/sites/all/modules/custom/fsa_guid/views/plugins/fsa_guid_views_plugin_row_node_rss.inc

Add various admin functions and views integration  …
* Added permission to administer GUIDs
* Added menu items for admin functions - GUID pattern and reset
* Added views hook to replace standard row style plugin for RSS
* Added useful constants
* Use tokens to create GUID pattern
[ Partial fix for #10357 ]

Develop: Improve GUID module

---

docroot/sites/all/modules/contrib/block_class/block_class.info
docroot/sites/all/modules/contrib/block_class/block_class.install
docroot/sites/all/modules/contrib/block_class/block_class.module
docroot/sites/all/modules/contrib/block_class/block_class.test
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.features.fe_block_settings.inc
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.info
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.module

Upgraded the block class contrib module from version 7.x-2.1 to 7.x-2.3.
This is a security release.
[ Fixes #10338 ]

Develop: Upgrade block class module to version 7.x 2.3

---

docroot/sites/all/modules/development/stage_file_proxy/INSTALL.txt
docroot/sites/all/modules/development/stage_file_proxy/stage_file_proxy.info
docroot/sites/all/modules/development/stage_file_proxy/stage_file_proxy.module

Ticket# 10481 - Stage File Proxy has been upgraded to version 7.x-1.7.

Upgrade Stage File Proxy to version 7.x-1.7

---

docroot/sites/all/modules/contrib/block_class/block_class.info
docroot/sites/all/modules/contrib/block_class/block_class.install
docroot/sites/all/modules/contrib/block_class/block_class.module
docroot/sites/all/modules/contrib/block_class/block_class.test
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.features.fe_block_settings.inc
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.info
docroot/sites/all/modules/contrib/block_class/tests/block_class_fe_block_test.module

Upgraded the block class contrib module from version 7.x-2.1 to
7.x-2.3. This is a security release.
[ Fixes #10338 ]

Upgrade block class module to version 7.x-2.3

---

docroot/sites/all/modules/contrib/block_class/block_class.info

Added an extra line break to the .info file so Git would see the change.
[ Partial fix for #10338 ]

Modify block_class.info so Git would pick it up

---

docroot/sites/all/modules/custom/local/css/local.css
docroot/sites/all/modules/custom/local/local.module
docroot/status.php

Develop: Accordion height fix in admin interface which got dynamically added by a Javascript file post field_group upgrade
Ticket: 10700

Develop: Accordion height fix in admin interface. Ticket: 10700

---

docroot/sites/all/modules/custom/local/css/local.css
docroot/sites/all/modules/custom/local/local.module
docroot/status.php

Accordion height in admin interface which was dynamically being added by a Javascript post field_group upgrade has been fixed now.
All that extra spaces between each accordion section have been removed
Scroll bars that were appearing due to this extra white spaces have disappeared

Master - Accordion height in admin interface has been fixed

---

docroot/sites/all/modules/custom/local/css/local.css

Accordion height fix to make it work in staging server.
Ticket#10700

Develop: Accordion height fix to make it work in staging server

---

docroot/sites/all/modules/custom/local/css/local.css

Accordion height fix to make it work in staging server
Ticket#10700

Accordion height fix to make it work in staging server

---

docroot/sites/all/modules/contrib/features/features.admin.inc
docroot/sites/all/modules/contrib/features/features.api.php
docroot/sites/all/modules/contrib/features/features.css
docroot/sites/all/modules/contrib/features/features.drush.inc
docroot/sites/all/modules/contrib/features/features.export.inc
docroot/sites/all/modules/contrib/features/features.info
docroot/sites/all/modules/contrib/features/features.install
docroot/sites/all/modules/contrib/features/features.js
docroot/sites/all/modules/contrib/features/features.module
docroot/sites/all/modules/contrib/features/includes/features.contact.inc
docroot/sites/all/modules/contrib/features/includes/features.field.inc
docroot/sites/all/modules/contrib/features/includes/features.image.inc
docroot/sites/all/modules/contrib/features/includes/features.locale.inc
docroot/sites/all/modules/contrib/features/includes/features.menu.inc
docroot/sites/all/modules/contrib/features/includes/features.node.inc
docroot/sites/all/modules/contrib/features/includes/features.user.inc
docroot/sites/all/modules/contrib/features/tests/features.test
docroot/sites/all/modules/contrib/features/tests/features_test/features_test.features.inc
docroot/sites/all/modules/contrib/features/tests/features_test/features_test.info
docroot/sites/all/modules/contrib/features/theme/features-admin-components.tpl.php
docroot/sites/all/modules/contrib/features/theme/theme.inc

Ticket: 10479 
Features module has been upgraded to version 7.x-2.10

Develop: Features module upgrade to version 7.x-2.10

---

docroot/sites/all/modules/contrib/features/features.admin.inc
docroot/sites/all/modules/contrib/features/features.api.php
docroot/sites/all/modules/contrib/features/features.css
docroot/sites/all/modules/contrib/features/features.drush.inc
docroot/sites/all/modules/contrib/features/features.export.inc
docroot/sites/all/modules/contrib/features/features.info
docroot/sites/all/modules/contrib/features/features.install
docroot/sites/all/modules/contrib/features/features.js
docroot/sites/all/modules/contrib/features/features.module
docroot/sites/all/modules/contrib/features/includes/features.contact.inc
docroot/sites/all/modules/contrib/features/includes/features.field.inc
docroot/sites/all/modules/contrib/features/includes/features.image.inc
docroot/sites/all/modules/contrib/features/includes/features.locale.inc
docroot/sites/all/modules/contrib/features/includes/features.menu.inc
docroot/sites/all/modules/contrib/features/includes/features.node.inc
docroot/sites/all/modules/contrib/features/includes/features.user.inc
docroot/sites/all/modules/contrib/features/tests/features.test
docroot/sites/all/modules/contrib/features/tests/features_test/features_test.features.inc
docroot/sites/all/modules/contrib/features/tests/features_test/features_test.info
docroot/sites/all/modules/contrib/features/theme/features-admin-components.tpl.php
docroot/sites/all/modules/contrib/features/theme/theme.inc

Upgraded the Features module to version 7.x-2.10
There is a database schema update included in this upgrade, so the following command should be run:
``drush updb --y``
[ Fixes #10479 ]

Upgrade Features module to version 7.x-2.10

---

docroot/sites/all/modules/contrib/httprl/LICENSE.txt
docroot/sites/all/modules/contrib/httprl/README.txt
docroot/sites/all/modules/contrib/httprl/examples/httprl.examples.php
docroot/sites/all/modules/contrib/httprl/httprl.admin.inc
docroot/sites/all/modules/contrib/httprl/httprl.async.inc
docroot/sites/all/modules/contrib/httprl/httprl.info
docroot/sites/all/modules/contrib/httprl/httprl.install
docroot/sites/all/modules/contrib/httprl/httprl.module

Added the HTTPRL contrib module. This will be used in conjunction with the new CloudFlare cache clear module to clear items from the CloudFlare cache.

10421: Add HTTPRL contrib module (develop)

---

docroot/sites/all/modules/custom/commitees_custom/commitees_custom.install
docroot/sites/all/modules/custom/commitees_custom/commitees_custom.module

Added functionality to grant access to all organic groups (committees) when a user has a new role.
[ Fixes #10506 ]

10506: Committee permissions

---

docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.info
docroot/sites/all/modules/custom/fsa_feedback/fsa_feedback.module
docroot/sites/all/modules/custom/fsa_feedback/views/fsa_feedback.views.inc
docroot/sites/all/modules/custom/fsa_feedback/views/fsa_feedback.views_default.inc
docroot/sites/all/modules/custom/fsa_feedback/views/fsa_feedback_views_handler_field_message_part.inc

Added new functionality for exporting feedback submissions to CSV format.
This involved:
* Creation of a new views field handler for feedback message parts
* Addition of a new view to select and export feedback submissions
* Modification of the existing page to display feedback submissions
* Modification of menu entries
[ Partial fix for #102874 ]

102874: Feedback submission export functionality (master)

---

docroot/sites/all/themes/committee_science_council/css/overrides.css
docroot/sites/all/themes/committee_science_council/sass/overrides.scss

Changed the dark blue colour for the Science Council committee theme to 0373afas requested by Sally.
[ Partial fix for 103497 ]

103497: Modify science council theme colour

---

docroot/sites/all/themes/committee_science_council/css/overrides.css
docroot/sites/all/themes/committee_science_council/sass/overrides.scss

Made some further modifications to the Science Council committee site colours as requested by Sally.
[ Partial fix for 103497 ]

103497: Modify science committee colours

---

docroot/sites/default/settings.php

Increased memoery limit from 512M to 700M.

Increase memory limit

---

docroot/sites/all/modules/custom/fsa_beta_banner/fsa_beta_banner.module

Removed the `noreferrer` attribute as not really needed here.
[ Partial fix for 105041 ]

105041: Remove noreferrer
